version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build
      - export BUCKET=businesspartner-api-devops
      - sam package --s3-bucket businesspartner-api-devops --s3-prefix lambdas --output-template-file outputtemplate.yml

artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
