AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda

Parameters:
  IAMRoleForCodeDeploy:
    Type: String
    Default: arn:aws:iam::843358133778:role/service-role/taller-14-11-2022-role-yt3h5csx
  EnvirontmentDeploy:
    Type: String
    Default: 'dev'

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Join ['-', [A_x, !Ref EnvirontmentDeploy]]
      CodeUri: .
      Handler: app.handler
      Role: arn:aws:iam::843358133778:role/service-role/taller-14-11-2022-role-yt3h5csx
      Runtime: python3.8
      Timeout: 60
      MemorySize: 2048
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Tags:
        Owner: Alberto Prieto
        App: X
        Proyecto: modernizacion de aplicativo
      Layers:
        - arn:aws:lambda:us-east-1:843358133778:layer:fastApi:1

  Api:
    Type: AWS::Serverless::HttpApi
    Name: !Join ['-', [L_x_API, !Ref EnvirontmentDeploy]]
    StageName: !Ref EnvirontmentDeploy
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - '*'
        AllowMethods:
          - '*'